### ISSUE TITLE
Needs to have a database in the influxdb at the start

### ISSUE THREAD

**Issue by goatchurchprime** [DynamicDevices/ming#1]
Needed to run this on my local PC connected to the access point.

```
from influxdb import InfluxDBClient
client = InfluxDBClient("mqttroam.local", 8086, "root", "bubblino", None)
print(client.get_list_database())
client.create_database("balena-sense")
print(client.get_list_database())

```

**Comment by goatchurchprime** [comment]
Also would need to document the prefered:

Username/password for the Grafana login
Username/password for the InfluxDB database
Username/password for the Nodered flow control

Username/password for the SSH of the device

These are all easy to get confused between, esp the Grafana and InfluxDB which almost seem like the same thing.

**Comment by ajlennon** [comment]
OK - seems like this could be run in the grafana container build process ?

**Comment by ajlennon** [comment]
You can use the InfluxDB API to do what you need, including creating databases e.g.

`curl 'http://e844144.local:8086/query' --data-urlencode "q=CREATE DATABASE mydb"`
