### ISSUE TITLE
Add Wifi-Hotspot support

### ISSUE THREAD

**Issue by MatthewCroughan** [DynamicDevices/ming#12]
I'm working on this now in my fork, I'm basing it on https://github.com/balena-io/wifi-connect.

**Comment by ajlennon** [comment]
Take a look at the MakeSpaceLive stuff. I had support for this in there. Also Adrian has worked with this. One problem that needs addressing is it sometimes fails to connect on startup and drops into AP mode which is not the behaviour we want

**Comment by MatthewCroughan** [comment]
@ajlennon Well for what we want, the whole behavior is not ideal anyway. What we want is to be able to connect it and disconnect it, currently if we were to connect it to the wifi we'd have no way of disconnecting it again easily. Maybe we can have a service variable that wipes the list of wifi credentials in order to drop it into AP mode again.

This is mostly to satisfy Julian's need of it being portable, for the time being until we figure out an ideal portable travel router to bundle with the thing. I think I can solve it dropping into AP mode permanently by having a time limiter on the shell command that runs wifi-connect, testing it all right now anyhow.

**Comment by MatthewCroughan** [comment]
On the topic of portable travel routers.. This could be an option to make one for SUPER cheap.. around £15~ 

![image](https://user-images.githubusercontent.com/26458780/68666244-76a5ad00-053b-11ea-81ff-1482866eacc6.png)

Two ETH ports a router does make :)

**Comment by ajlennon** [comment]
Nice. I remain  very unconvinced though that we can run a Pi as an AP and have a lot of sensors connected...

**Comment by ajlennon** [comment]
Like those. Are those Atheros chips dual band ?

**Comment by MatthewCroughan** [comment]
Done in https://github.com/DynamicDevices/ming/pull/13.

@ajlennon as for the question about the chips being dual band, they aren't, but you can get variants like that, more expensive obviously. I think these would be a great start.

**Comment by ajlennon** [comment]
This is a variant of the GL-AR750 which we were using to begin with for the WiFi security project!

**Comment by MatthewCroughan** [comment]
@ajlennon So you have a few lying around then? Would love to try them out.

**Comment by ajlennon** [comment]
I might do actually! Will take a look around

**Comment by ajlennon** [comment]
Merged the PR
