### ISSUE TITLE
Give me push access.

### ISSUE THREAD

**Issue by MatthewCroughan** [DynamicDevices/ming#17]
Once I have push access, I can reference issues in commits, like I'm about to demonstrate.

https://github.com/DynamicDevices/ming/issues/16

**Comment by MatthewCroughan** [comment]
https://github.com/DynamicDevices/ming/issues/16

**Comment by ajlennon** [comment]
Yup. How do we do that then?

**Comment by ajlennon** [comment]
I'm almost certain you can reference issues in commits without push access too ?

**Comment by MatthewCroughan** [comment]
Does indeed work.
