### ISSUE TITLE
Enable Mosquitto websockets by default 

### ISSUE THREAD

**Issue by ajlennon** [DynamicDevices/ming#20]
eg 

https://blog.ithasu.org/2016/05/enabling-and-using-websockets-on-mosquitto/

**Comment by ajlennon** [comment]
Fancy a go @MatthewCroughan ?

**Comment by MatthewCroughan** [comment]
Are there any security implications? Is there a reason mosquitto doesn't enable it by default anyway @ajlennon ?

**Comment by ajlennon** [comment]
Good questions.

**Comment by MatthewCroughan** [comment]
I think I'll look around and put that in the PR and discuss what I find regarding security, maybe enable it depending on env vars.

**Comment by ajlennon** [comment]
Response from Roger Light (Mosquitto creator)

"Security is much the same as for normal MQTT. Biggest difference is probably in keeping your credentials secret if you're using it as a web interface."
