### ISSUE TITLE
Nodered should have the nodered dashboards set up

### ISSUE THREAD

**Issue by goatchurchprime** [DynamicDevices/ming#3]
I don't know why these aren't default part of the installation.  Gives the ability to make buttons and dials (which the Grafana is no good at).

**Comment by ajlennon** [comment]
What's missing and what needs doing ?

**Comment by MatthewCroughan** [comment]
@goatchurchprime Have you got a list of the things you want? 

@ajlennon  Perhaps we could have a list of modules to be installed in the balena build available in the repo so we can then `COPY` it in via the Dockerfile.

**Comment by MatthewCroughan** [comment]
When I say a list, I mean a list that we install via `npm install -g`, not something that is static.

**Comment by ajlennon** [comment]
This is now setup by default
