### ISSUE TITLE
How to access local mosquitto broker?

### ISSUE THREAD

**Issue by alexcorvis84** [DynamicDevices/ming#35]
What should be the address to conect to local mosquitto broker deployed from a MQTT node in Node-RED?

localhost:1883 does not work

I guess it should be possible, right? What should be the host address then?

Thanks in advance!

**Comment by ajlennon** [comment]
If mosquitto is running then the default Docker.compse maps through 1883 so that should work

https://github.com/DynamicDevices/ming/blob/master/docker-compose.yml#L42

You might try the WiFi/LAN IP address?

Also Traefik should map through to this if I recall

**Comment by ajlennon** [comment]
Have a look at this work I did to use Traefik to map through from a single public URL on an IP address to multiple internal ports

https://github.com/DynamicDevices/reverse-proxy

**Comment by alexcorvis84** [comment]
> If mosquitto is running then the default Docker.compse maps through 1883 so that should work
> 
> https://github.com/DynamicDevices/ming/blob/master/docker-compose.yml#L42
> 
> You might try the WiFi/LAN IP address?
> 
> Also Traefik should map through to this if I recall

My fault, I mixed different systems I have on balena and setup the wrong IP address 🤦🏼‍♂️  Now it's working! 

Apologies and thank you so much for your quick reply Alex! You can close the issue ;-)

**Comment by ajlennon** [comment]
Awesome !!! Can you help me out? There's a bunch of things I want to do with MING but haven't had the time. Have had chats with @mpous about this as he's been a lot more active than me recently. I'd love to know your experience of using the stack, what works, what doesn't work, where things could be improved - particularly easy wins like documentation. Cheers !!!
