### ISSUE TITLE
When running in AP mode the time is incorrect

### ISSUE THREAD

**Issue by ajlennon** [DynamicDevices/ming#4]

**Comment by ajlennon** [comment]
Currently we have support for an I2C battery backed RTC device to deal with this issue.

Code looks like it still needs to be committed

**Comment by ajlennon** [comment]
Quoting gtp "Alex has ordered this: https://www.amazon.co.uk/DS3231-RTC-MODULE-RASPBERRY-PI/dp/B01I1I8HY8 Though there still needs to be a provision to set the time initially."

**Comment by MatthewCroughan** [comment]
@ajlennon What needs to be done in order to apply this?

**Comment by ajlennon** [comment]
We either have to add an I2C RTC device onto every board or to find a way to use an NTP client to grab the time from the Internet on startup.

**Comment by MatthewCroughan** [comment]
@goatchurchprime Julian has suggested a few methods of getting time. One method he suggested included having time emitted as mqtt messages from some device that has an RTC. You could then add nodes as ENV variables in balena by using either their expected IP or hostname.

**Comment by ajlennon** [comment]
Yeah not a bad idea but it adds a dependency on another device which I'd rather not have. If we had to have a dependency I'd rather have one on an internal I2C RTC

**Comment by MatthewCroughan** [comment]
@ajlennon Why not both? More sources of time the better, like /dev/random gets its randomness from every place it can, this is like /dev/time.

**Comment by ajlennon** [comment]
Mmm. Not really. Time is a problem. Which time source is preferable?

A local I2C RTC time source is probably accurate to a minute a month so needs to be regularly updated with a more accurate time source which would be GPS or network time...

**Comment by ajlennon** [comment]
Currently not intending to run in AP mode so closing this
