### ISSUE TITLE
Disable wifi when connected by ethernet

### ISSUE THREAD

**Issue by goatchurchprime** [DynamicDevices/ming#5]
At the moment we are getting 2 IP numbers for the device because it's going both routes.  

Prefer only one, and the ethernet when wired as we think it would have lower latency.  

this should be something each device checks intermittently, along with sending its ip and mac address. it should send to a channel it is subscribed to and then send a message again to report the round trip time.

**Comment by ajlennon** [comment]
For now on the host OS image if you want to disable the WiFI then edit files in the /boot partition (which can be seen as a FAT partition on a Windows PC too)

`$ mv /mnt/boot/system-connections/resin-wifi-01 /mnt/boot/system-connections/resin-wifi-01.ignore`

This will disable the WiFi connection enabling you to use Ethernet reliably
